services:
  - type: web
    name: swiftcart-web
    env: python
    repo: https://github.com/onikageyoshi/E-COMMERCE_API_FORM
    branch: main
    buildCommand: "./build.sh"
    startCommand: gunicorn ecommerce_api_form.wsgi:application --bind 0.0.0.0:8000

    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
